#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_FILE="${1:-$ROOT_DIR/init_compact.lua}"

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

emit_lua_string() {
  local file="$1"
  local eq=""

  while grep -q "]${eq}]" "$file"; do
    eq="${eq}="
  done

  printf "[%s[\n" "$eq" >>"$TMP_FILE"
  cat "$file" >>"$TMP_FILE"
  printf "]%s]" "$eq" >>"$TMP_FILE"
}

lua_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  printf "%s" "$value"
}

emit_chunk_loader() {
  local path="$1"
  printf "assert(load(" >>"$TMP_FILE"
  emit_lua_string "$path"
  printf ", \"%s\", \"t\", _ENV))()\n" "$(lua_escape "@${path#$ROOT_DIR/}")" >>"$TMP_FILE"
}

emit_vim_loader() {
  local path="$1"
  printf "vim.cmd(" >>"$TMP_FILE"
  emit_lua_string "$path"
  printf ")\n" >>"$TMP_FILE"
}

emit_runtime_file() {
  local path="$1"

  case "$path" in
    *.lua) emit_chunk_loader "$path" ;;
    *.vim) emit_vim_loader "$path" ;;
  esac
}

emit_preload() {
  local module_name="$1"
  local path="$2"

  printf "package.preload[\"%s\"] = function(...)\n" "$(lua_escape "$module_name")" >>"$TMP_FILE"
  printf "  return assert(load(" >>"$TMP_FILE"
  emit_lua_string "$path"
  printf ", \"%s\", \"t\", _ENV))(...)\n" "$(lua_escape "@${path#$ROOT_DIR/}")" >>"$TMP_FILE"
  printf "end\n\n" >>"$TMP_FILE"
}

module_name_for() {
  local path="$1"
  local rel="${path#$ROOT_DIR/lua/}"
  rel="${rel%.lua}"
  rel="${rel//\//.}"
  printf "%s\n" "$rel"
}

emit_module_preloads() {
  if [[ ! -d "$ROOT_DIR/lua" ]]; then
    return
  fi

  while IFS= read -r path; do
    local module_name
    module_name="$(module_name_for "$path")"
    emit_preload "$module_name" "$path"

    if [[ "$module_name" == *.init ]]; then
      emit_preload "${module_name%.init}" "$path"
    fi
  done < <(find "$ROOT_DIR/lua" -type f -name "*.lua" | sort)
}

emit_runtime_dir() {
  local runtime_dir="$1"

  if [[ ! -d "$ROOT_DIR/$runtime_dir" ]]; then
    return
  fi

  while IFS= read -r path; do
    emit_runtime_file "$path"
  done < <(find "$ROOT_DIR/$runtime_dir" -type f \( -name "*.lua" -o -name "*.vim" \) | sort)
}

emit_ftplugin_dir() {
  local ft_dir="$1"

  if [[ ! -d "$ROOT_DIR/$ft_dir" ]]; then
    return
  fi

  while IFS= read -r ft; do
    local escaped_ft
    escaped_ft="${ft//[^a-zA-Z0-9_]/_}"

    printf "vim.api.nvim_create_autocmd(\"FileType\", {\n" >>"$TMP_FILE"
    printf "  pattern = \"%s\",\n" "$(lua_escape "$ft")" >>"$TMP_FILE"
    printf "  group = vim.api.nvim_create_augroup(\"%s\", { clear = true }),\n" "$(lua_escape "compact_ftplugin_${ft_dir//\//_}_$escaped_ft")" >>"$TMP_FILE"
    printf "  callback = function(args)\n" >>"$TMP_FILE"

    while IFS= read -r path; do
      local rel key
      rel="${path#$ROOT_DIR/}"
      key="compact_loaded_${rel//[^a-zA-Z0-9_]/_}"
      printf "    if vim.b[args.buf][\"%s\"] then\n" "$(lua_escape "$key")" >>"$TMP_FILE"
      printf "      return\n" >>"$TMP_FILE"
      printf "    end\n" >>"$TMP_FILE"
      printf "    vim.b[args.buf][\"%s\"] = true\n" "$(lua_escape "$key")" >>"$TMP_FILE"
      case "$path" in
        *.lua)
          printf "    assert(load(" >>"$TMP_FILE"
          emit_lua_string "$path"
          printf ", \"%s\", \"t\", _ENV))()\n" "$(lua_escape "@$rel")" >>"$TMP_FILE"
          ;;
        *.vim)
          printf "    vim.cmd(" >>"$TMP_FILE"
          emit_lua_string "$path"
          printf ")\n" >>"$TMP_FILE"
          ;;
      esac
    done < <(
      find "$ROOT_DIR/$ft_dir/$ft" -type f \( -name "*.lua" -o -name "*.vim" \) 2>/dev/null
      find "$ROOT_DIR/$ft_dir" -maxdepth 1 -type f \( -name "$ft.lua" -o -name "$ft.vim" \) 2>/dev/null
    )

    printf "  end,\n" >>"$TMP_FILE"
    printf "})\n\n" >>"$TMP_FILE"
  done < <(
    {
      find "$ROOT_DIR/$ft_dir" -mindepth 1 -maxdepth 1 -type d -printf "%f\n"
      find "$ROOT_DIR/$ft_dir" -mindepth 1 -maxdepth 1 -type f \( -name "*.lua" -o -name "*.vim" \) -printf "%f\n" | sed -E 's/\.(lua|vim)$//'
    } | sort -u
  )
}

{
  printf -- "-- Generated by compact.sh. Do not edit directly.\n"
  printf -- "-- Source layout bundled from init.lua, lua/, plugin/, after/plugin/, ftplugin/, after/ftplugin/.\n\n"
  printf "local package = package\n\n"
} >"$TMP_FILE"

emit_module_preloads

printf -- "-- init.lua\n" >>"$TMP_FILE"
emit_chunk_loader "$ROOT_DIR/init.lua"
printf "\n" >>"$TMP_FILE"

printf -- "-- plugin/*.lua\n" >>"$TMP_FILE"
emit_runtime_dir "plugin"
printf "\n-- after/plugin/*.lua\n" >>"$TMP_FILE"
emit_runtime_dir "after/plugin"
printf "\n-- ftplugin hooks\n" >>"$TMP_FILE"
emit_ftplugin_dir "ftplugin"
printf "\n-- after/ftplugin hooks\n" >>"$TMP_FILE"
emit_ftplugin_dir "after/ftplugin"

mv "$TMP_FILE" "$OUT_FILE"
