require "plugins.core"
require "plugins.ui"
require "plugins.editing"
require "plugins.generators"
require "plugins.navigation"
require "plugins.lsp"
require "plugins.integrations.discord"
require "plugins.integrations.databases"
